### PR TITLE
update curatedTCGAData function call

### PR DESCRIPTION
**Pull request by LiNk-NY**
Hi Olivier, @ogevaert 
We are getting ready to release our data version 2 of curatedTCGAData. 
I've updated the code to use the 'previous' release.
This should resolve the errors in the report: 
http://bioconductor.org/checkResults/devel/bioc-LATEST/AMARETTO/

Best,
Marcel

### CODE REVIEW

**Comment by LiNk-NY** [comment]
Olivier, @ogevaert 
Please review and merge the pull request for your packages continued inclusion in Bioconductor. 
If you have any questions, contact me here by mentioning my tag (@LiNk-NY). Thanks!

**Comment by LiNk-NY** [comment]
Hi Olivier, @ogevaert, Jayendra @jayendrashinde91 also @monabiyan @celineeveraert @shebak11
Any updates on this? Otherwise the package will be deprecated due to a lack of response.

**Comment by ogevaert** [comment]
Hi Marcel

We are working on this, my apologies for the  slow response,

Olivier

**Comment by LiNk-NY** [comment]
Thank you!
**PS**. Please be aware that we have a new data release coming out version `2.0.1`. 
See the `curatedTCGAData` `NEWS.md` file and documentation for more details. 
Best,
Marcel

**Comment by shebak11** [comment]
Hi @LiNk-NY @ogevaert 
I have emailed bioc-devel@r-project.org asking to be added as a maintainer of the package. 
Best,
Shaimaa

**Pull request merged**
